# Generated by Django 4.2.6 on 2023-10-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_remove_bookmark_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookshelves',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='text_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
