# Generated by Django 4.2.6 on 2023-10-26 11:01

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "dataset.json")


class Migration(migrations.Migration):

    dependencies = [
        ('pengelola', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
