# Generated by Django 4.2.6 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='nama_buku',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nama_penulis',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tahun',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
